language: rust
rust:
  - stable
script:
  - cargo build --release --verbose
os:
  - windows
  - osx
cache: cargo
deploy:
  provider: releases
  api_key:
    secure: Pcb7k4/UkNFm1g+v5DHx7qoKaTjOyiGn5JeKeVUotkFvM0sehAEZDnjQOw6mAPVxFs6oUIlF7lDzSMZjjx9i3eW3r6TIDZgmVLkF4xAdAOHYJXaLKIcXGwtfSOS7xORPFRjhzcl7yUotCHMdG2BGVKJdkgB2GKyk/Ft7pLXAxbduPQN1Vx41X3MDUMSpXbwH2kh5DRhlYhsj0keD64IxxN6DYeA4+t5UpX8Ajkfpd7F7xUTjdXybX6tDkW7rwav1O6SOZEJcq+vLnx/uItF8BFnN93DHhc0mHmYtPCckQhFG/U85KR9FPC4ybVa3ii6ewhM5wcLf9x6uai/8E5LVpvOJdN8+Vd2fKHEqwWpenn+27Oy6HnrXlXm91cwCfZfYh2IqiNftvqI7g5zQyeN7e+atCka+yC0p8o8CdtGMbPTjBN82Ge/eP8KNrKdUXQDI3Eh0haJxayyWk9XOBSs/2sPXTNobzYTsIXx8n6ABmV5ijLj4xnHTWPqmn47WcvZVAwFz1TjE/zznz6ukjqY3p98Xt83eUYr4MIlkcdMrQUfIBv+UbALrhrFnfL8dErzs6DUndFwyhQwHAfHGvEC4NjlHoIHSjQrL3l0XcRhxyytYS6yCd87OP5dqXK52myQyY01dOGh6vLisjWlBSTZZZ50f0RLa8+OTwloTk9TSvf4=
  file_glob: true
  file: target/release/adobe-license-{decoder,decoder.exe}
  on:
    tags: true
    repo: adobe/adobe-license-decoder.rs
  skip_cleanup: 'true'
