[package]
name = "adobe_license_decoder"
version = "0.1.0"
authors = ["Daniel Brotsky <dbrotsky@adobe.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
base64 = "0.13.0"
shellexpand = "2.0.0"
chrono = "0.4.19"
glob = "0.3.0"

[[bin]]
name = "adobe-license-decoder"
path = "src/main.rs"