on: [workflow_dispatch, push, pull_request]

name: Rust CI (stable)

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Build debug
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build release locked
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked

      - name: Format check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Upload executables
        uses: actions/upload-artifact@v2
        with:
          name: executables
          path: |
            target/*/adobe-license-decoder
            target/*/adobe-license-decoder.exe
