name: Publish executables

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: adobe-license-decoder.exe
            asset_name: adobe-license-decoder.exe
          - os: macos-latest
            artifact_name: adobe-license-decoder
            asset_name: adobe-license-decoder

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build release locked
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked

      - name: Post release executable
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
